### ISSUE TITLE
/usr/bin/ld: crti.o: No such file: No such file or directory 

### ISSUE THREAD

**Issue by bcfarmers** [3rd-Eden/memcached#250]
Unable to install memcached on RedHat. The install continues to fail on installation on hashring. glibc-devel and gcc-c++ are installed.

hashring@3.1.1 install /opt/node-v0.12.2-linux-x86/bin/node_modules/memcached/node_modules/hashring
node-gyp rebuild
make: Entering directory /opt/node-v0.12.2-linux-x86/bin/node_modules/memcached/node_modules/hashring/build' CXX(target) Release/obj.target/hashvalue/src/hashvalue.o SOLINK_MODULE(target) Release/obj.target/hashvalue.node /usr/bin/ld: crti.o: No such file: No such file or directory collect2: ld returned 1 exit status make: *** [Release/obj.target/hashvalue.node] Error 1 make: Leaving directory/opt/node-v0.12.2-linux-x86/bin/node_modules/memcached/node_modules/hashring/build'
gyp ERR! build error
gyp ERR! stack Error: make failed with exit code: 2
gyp ERR! stack at ChildProcess.onExit (/opt/node-v0.12.2-linux-x86/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack at ChildProcess.emit (events.js:110:17)
gyp ERR! stack at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 2.6.32-504.16.2.el6.x86_64
gyp ERR! command "node" "/opt/node-v0.12.2-linux-x86/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/node-v0.12.2-linux-x86/bin/node_modules/memcached/node_modules/hashring
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm ERR! Linux 2.6.32-504.16.2.el6.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "memcached"
npm ERR! node v0.12.2
npm ERR! npm v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! hashring@3.1.1 install: node-gyp rebuild
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hashring@3.1.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the hashring package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node-gyp rebuild
npm ERR! You can get their info via:
npm ERR! npm owner ls hashring
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
######

402 info hashring@3.1.1 Failed to exec install script
403 verbose unlock done using /root/.npm/_locks/hashring-3b9afffda91c7089.lock for /opt/node-v0.12.2-linux-x86/bin/node_modules/hashring
404 verbose stack Error: hashring@3.1.1 install: node-gyp rebuild
404 verbose stack Exit status 1
404 verbose stack at EventEmitter. (/opt/node-v0.12.2-linux-x86/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
404 verbose stack at EventEmitter.emit (events.js:110:17)
404 verbose stack at ChildProcess. (/opt/node-v0.12.2-linux-x86/lib/node_modules/npm/lib/utils/spawn.js:14:12)
404 verbose stack at ChildProcess.emit (events.js:110:17)
404 verbose stack at maybeClose (child_process.js:1015:16)
404 verbose stack at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
405 verbose pkgid hashring@3.1.1
406 verbose cwd /opt/node-v0.12.2-linux-x86/bin
407 error Linux 2.6.32-504.16.2.el6.x86_64
408 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "hashring"
409 error node v0.12.2
410 error npm v2.7.4
411 error code ELIFECYCLE
412 error hashring@3.1.1 install: node-gyp rebuild
412 error Exit status 1
413 error Failed at the hashring@3.1.1 install script 'node-gyp rebuild'.
413 error This is most likely a problem with the hashring package,
413 error not with npm itself.
413 error Tell the author that this fails on your system:
413 error node-gyp rebuild
413 error You can get their info via:
413 error npm owner ls hashring
413 error There is likely additional logging output above.
414 verbose exit [ 1, true ]
415 verbose unbuild node_modules/hashring
416 info preuninstall hashring@3.1.1
417 info uninstall hashring@3.1.1
418 verbose unbuild rmStuff hashring@3.1.1 from /opt/node-v0.12.2-linux-x86/bin/node_modules
419 info postuninstall hashring@3.1.1
420 silly gentlyRm /opt/node-v0.12.2-linux-x86/bin/node_modules/hashring is being purged from base /opt/node-v0.12.2-linux-x86/bin
421 verbose gentlyRm don't care about contents; nuking /opt/node-v0.12.2-linux-x86/bin/node_modules/hashring
422 silly vacuum-fs purging /opt/node-v0.12.2-linux-x86/bin/node_modules/hashring
423 silly vacuum-fs quitting because other entries in /opt/node-v0.12.2-linux-x86/bin/node_modules

**Comment by 3rd-Eden** [comment]
I can't really do anything about that sorry. It's obviously missing something on your system here as it complains about a missing `/usr/bin/ld:` 

The thing here is, the hashring module has no dependencies other than NaN. It's a simple c++ function that does bit shifting and has now OS based dependencies. So if anything there fails it's like the fault of missing packages on your system or mess up by `node-gyp` which runs the actual installation and creation of the installation files.
