### ISSUE TITLE
memcached-2.1.0 give ENOENT error, but works fine with 0.2.8

### ISSUE THREAD

**Issue by vsacheti** [3rd-Eden/memcached#252]
Hello, I am trying to connect memcached to a server listening on socket, it works perfectly fine with `memcached-0.2.8` but gives me `ENOENT` error with the latest `memcached-2.1.0`.

I am getting following error
```
{ [Error: connect ENOENT] code: 'ENOENT', errno: 'ENOENT', syscall: 'connect' } 'Error: connect ENOENT\n    at errnoException (net.js:905:11)\n    at Object.afterConnect [as oncomplete] (net.js:896:19)' 'ENOENT' 'connect ENOENT'
```

My code looks something like this
```
var options= {
                retries: 1,
                retry: 60000,                // one minute (in milliseconds)
                reconnect: 60000             // one minute (in milliseconds)
            };
var Memcached = require('memcached');
var memcached = new Memcached('/tmp/.memcached.sock', options);
memcached.set( "hello", 1, 10000, function( err, result ){
	if( err ) console.error( err );
	
	console.dir( result );
	memcached.end(); // as we are 100% certain we are not going to use the connection again, we are going to end it
});
```

Any help will be really appreciated.

**Comment by vsacheti** [comment]
On looking at it closely, I found something in the code, which doesnt look right to me,

https://github.com/3rd-Eden/memcached/blob/master/lib/memcached.js#L135
```
if(!server.match(/(.+):(\d+)$/)) {
        server = server + ':11211';
    }
```
Here although the server is specified by a socket, it still appends the port, which is causing the `ENOENT` error.

**Comment by vsacheti** [comment]
Submitted a PR for this issue - https://github.com/3rd-Eden/memcached/pull/253

**Comment by drewfish** [comment]
This looks like another instance of issue #242 .

**Comment by ebaioni** [comment]
👍
