### ISSUE TITLE
master seems can not pass test cases?

### ISSUE THREAD

**Issue by mapleeit** [3rd-Eden/memcached#326]
# repro 
1. `brew services start memcached`
1. `git clone https://github.com/3rd-Eden/memcached.git`
2. `cd memcached`
3. `npm install`
4. `export MEMCACHED__HOST=localhost `
4. `memcached -p 11212 -d `
4. `memcached -p 11213 -d `
4. `npm test`

# result

```
 47 passing (19s)
  2 failing

  1) Memcached connections
       should return error on connection timeout:
     Uncaught Error: connect EACCES 10.255.255.255:1234 - Local (10.19.93.213:51450)
      at Object._errnoException (util.js:992:11)
      at _exceptionWithHostPort (util.js:1014:20)
      at internalConnect (net.js:960:16)
      at defaultTriggerAsyncIdScope (internal/async_hooks.js:284:19)
      at net.js:1058:9
      at _combinedTickCallback (internal/process/next_tick.js:131:7)
      at process._tickCallback (internal/process/next_tick.js:180:9)

  2) Memcached connections
       should reset failures if all failures do not occur within failuresTimeout ms:
     Uncaught Error: connect EACCES 10.255.255.255:1234 - Local (10.19.93.213:51454)
      at Object._errnoException (util.js:992:11)
      at _exceptionWithHostPort (util.js:1014:20)
      at internalConnect (net.js:960:16)
      at defaultTriggerAsyncIdScope (internal/async_hooks.js:284:19)
      at net.js:1058:9
      at _combinedTickCallback (internal/process/next_tick.js:131:7)
      at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by mapleeit** [comment]
I found the reason. My Mac is in company's LAN that the range of IP address is 10.0.0.0 - 10.255.255.255. So the 10.255.255.255 is the gateways of internal LAN, which isn't a non routable IP.
